name: dad-joke-email

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.2' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script 
        env: 
          SENDER: ${{ secrets.EMAIL_ADDRESS }}
          PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python email_creation.py
